#!/bin/bash

echo 'Running ruff check'
if ! ./.venv/bin/ruff check --config=ruff.toml; then
    echo
    echo
    echo "=========================================================================="
    echo "Ruff check failed. Please review the errors above.                         "
    echo "For a better development experience, it is recommended to configure the    "
    echo "ruff plugin for your IDE or use command-line tools. For more details,      "
    echo "refer to the CODE_CONVENTION.md file.                                      "
    echo "=========================================================================="
    exit 1
fi
