repos:
- repo: local
  hooks:
    - id: mypy-hook
      name: Custom mypy hook
      entry: bash .githooks/mypy
      language: system
      types: [python]
    - id: ruff-hook
      name: Custom ruff hook
      entry: bash .githooks/ruff
      language: system
      types: [python]
