name: Mirror to Git Repositories

on:
  push:
    branches:
      - main
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add remotes
        run: |
          git remote add gitflic https://aerodisk_open_vair:${{ secrets.GITFLIC_TOKEN }}@gitflic.ru/project/aerodisk_open_vair/openvair.git
          git remote add gitlab https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@git.aerodisk.ru/openvair/openvair.git
          git remote add gitverse https://Aerodisk:${{ secrets.GITVERSE_TOKEN }}@gitverse.ru/Aerodisk/openvair.git

      - name: Fetch all branches
        run: git fetch --unshallow --tags || git fetch --all

      - name: Force push to GitFlic
        run: |
          git push --force gitflic || echo "Push to GitFlic failed."

      - name: Force push to GitLab
        run: |
          git push --force gitlab || echo "Push to GitLab failed."

      - name: Force push to GitVerse
        run: |
          git push --force gitverse || echo "Push to GitVerse failed."
