name: Mirror to GitFlic

on:
  push:
    branches:
      - main
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add gitflic remote
        run: |
          git remote add gitflic https://$GIT_HTTPS_USER:$GIT_HTTPS_PASSWORD@gitflic.ru/project/aerodisk_open_vair/openvair.git

      - name: Force push to GitFlic
        run: |
          git push --force gitflic
        env:
          GIT_HTTPS_USER: "${{ secrets.GIT_USERNAME }}"
          GIT_HTTPS_PASSWORD: "${{ secrets.GIT_FLIC_PASSWORD }}"
