name: Mirror to GitFlic

on:
  push:
    branches:
      - main
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Add GitFlic remote
        run: git remote add gitflic https://gitflic.ru/project/aerodisk_open_vair/openvair.git

      - name: Force push to GitFlic
        run: |
          git config --global user.name "${{ secrets.GIT_USERNAME }}"
          git config --global user.password "${{ secrets.GIT_FLIC_PASSWORD }}"
          git push --force gitflic
        env:
          GIT_HTTPS_USER: "${{ secrets.GIT_USERNAME }}"
          GIT_HTTPS_PASSWORD: "${{ secrets.GIT_FLIC_PASSWORD }}"
