name: Mirror to GitFlic

on:
  push:
    branches:
      - main
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GITFLIC_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitflic.ru >> ~/.ssh/known_hosts

      - name: Add gitflic remote
        run: |
          git remote add gitflic git@gitflic.ru:project/aerodisk_open_vair/openvair.git

      - name: Force push to GitFlic
        run: |
          git push --force gitflic --all
          git push --force gitflic --tags
